<?php

// Subscription-provider catalog for rule-based Gmail detection.
// Each key MUST match the SP2 brand-color catalog key so imported
// subscriptions render with the right planet color.
return [
    'netflix' => [
        'name' => 'Netflix',
        'sender_domains' => ['netflix.com', 'members.netflix.com'],
        'payment_keywords' => ['receipt', 'payment', 'hóa đơn', 'gia hạn'],
        'cancellation_keywords' => ['cancelled', 'canceled', 'membership ended', 'đã hủy'],
        'amount_regex' => '/(?:US)?\$\s?([0-9][0-9.,]*)/',
        'default_currency' => 'USD',
        'default_cycle' => 'monthly',
        'cancel_url' => 'https://www.netflix.com/cancelplan',
    ],
    'spotify' => [
        'name' => 'Spotify',
        'sender_domains' => ['spotify.com'],
        'payment_keywords' => ['receipt', 'payment', 'premium'],
        'cancellation_keywords' => ['cancelled', 'canceled', 'subscription ended'],
        'amount_regex' => '/(?:US)?\$\s?([0-9][0-9.,]*)/',
        'default_currency' => 'USD',
        'default_cycle' => 'monthly',
        'cancel_url' => 'https://www.spotify.com/account/subscription/',
    ],
    'youtube' => [
        'name' => 'YouTube Premium',
        'sender_domains' => ['youtube.com'],
        'payment_keywords' => ['receipt', 'payment', 'youtube premium'],
        'cancellation_keywords' => ['cancelled', 'canceled', 'membership paused'],
        'amount_regex' => '/(?:US)?\$\s?([0-9][0-9.,]*)/',
        'default_currency' => 'USD',
        'default_cycle' => 'monthly',
        'cancel_url' => 'https://www.youtube.com/paid_memberships',
    ],
    'chatgpt' => [
        'name' => 'ChatGPT Plus',
        'sender_domains' => ['openai.com', 'stripe.com'],
        'payment_keywords' => ['receipt', 'payment', 'chatgpt'],
        'cancellation_keywords' => ['cancelled', 'canceled', 'subscription ended'],
        'amount_regex' => '/(?:US)?\$\s?([0-9][0-9.,]*)/',
        'default_currency' => 'USD',
        'default_cycle' => 'monthly',
        'cancel_url' => 'https://chatgpt.com/#settings',
    ],
    'google' => [
        'name' => 'Google One',
        'sender_domains' => ['google.com', 'payments.google.com'],
        'payment_keywords' => ['google one', 'receipt', 'payment'],
        'cancellation_keywords' => ['cancelled', 'canceled', 'membership ended'],
        'amount_regex' => '/(?:US)?\$\s?([0-9][0-9.,]*)/',
        'default_currency' => 'USD',
        'default_cycle' => 'monthly',
        'cancel_url' => 'https://one.google.com/',
    ],
    'adobe' => [
        'name' => 'Adobe',
        'sender_domains' => ['adobe.com', 'mail.adobe.com'],
        'payment_keywords' => ['receipt', 'invoice', 'payment'],
        'cancellation_keywords' => ['cancelled', 'canceled', 'plan cancelled'],
        'amount_regex' => '/(?:US)?\$\s?([0-9][0-9.,]*)/',
        'default_currency' => 'USD',
        'default_cycle' => 'monthly',
        'cancel_url' => 'https://account.adobe.com/plans',
    ],
    'apple' => [
        'name' => 'Apple',
        'sender_domains' => ['apple.com', 'email.apple.com'],
        'payment_keywords' => ['receipt', 'your invoice', 'subscription'],
        'cancellation_keywords' => ['cancelled', 'canceled', 'subscription ended'],
        'amount_regex' => '/(?:US)?\$\s?([0-9][0-9.,]*)/',
        'default_currency' => 'USD',
        'default_cycle' => 'monthly',
        'cancel_url' => 'https://apps.apple.com/account/subscriptions',
    ],
    'amazon' => [
        'name' => 'Amazon Prime',
        'sender_domains' => ['amazon.com', 'primevideo.com'],
        'payment_keywords' => ['prime', 'receipt', 'payment', 'membership'],
        'cancellation_keywords' => ['cancelled', 'canceled', 'membership ended'],
        'amount_regex' => '/(?:US)?\$\s?([0-9][0-9.,]*)/',
        'default_currency' => 'USD',
        'default_cycle' => 'yearly',
        'cancel_url' => 'https://www.amazon.com/gp/primecentral',
    ],
    'disney' => [
        'name' => 'Disney+',
        'sender_domains' => ['disneyplus.com', 'mail.disneyplus.com'],
        'payment_keywords' => ['receipt', 'payment', 'subscription'],
        'cancellation_keywords' => ['cancelled', 'canceled', 'subscription ended'],
        'amount_regex' => '/(?:US)?\$\s?([0-9][0-9.,]*)/',
        'default_currency' => 'USD',
        'default_cycle' => 'monthly',
        'cancel_url' => 'https://www.disneyplus.com/account/subscription',
    ],
];
